version: "3.9"

# Usage:
#   cp .env.neon.example .env.neon  # fill DATABASE_URL with Neon "pooled" URL
#   docker compose -f prod-lite-compose.yml --env-file .env.neon up -d --build
#
# Services: ui, server, caddy, and a one-shot "migrate" job.
# Postgres lives on Neon (serverless). Keeps FREE_MODE=true.
services:
  migrate:
    build:
      context: ./server
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    command: sh -lc "npx prisma migrate deploy"
    restart: "no"

  server:
    build:
      context: ./server
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      NODE_ENV: production
      FREE_MODE: "true"
      DATABASE_URL: ${DATABASE_URL}
      PORT: "4000"
    volumes:
      - ./server/var/uploads:/app/var/uploads
    expose:
      - "4000"
    restart: unless-stopped

  ui:
    build:
      context: ./ui
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://${DOMAIN}
    depends_on:
      - server
    expose:
      - "3000"
    restart: unless-stopped

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL:-admin@${DOMAIN}}
    volumes:
      - ./Caddyfile.free:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data: {}
  caddy_config: {}
