global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'qikiworld-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['server:4000']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

- job_name: 'qikiworld-worker'
  metrics_path: /metrics
  static_configs:
    - targets: ['worker:4001']
