name: CI (ui)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ui
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm i
          fi

      - name: Build
        run: npm run build

      - name: Upload .next (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: ui/.next
