name: Lighthouse

on:
  pull_request:

jobs:
  lhci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Start Next (prod)
        run: |
          npm run start -- -p 3000 &
          npx -y wait-on@7 http://localhost:3000

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npx -y @lhci/cli@0.13.0 autorun             --collect.url=http://localhost:3000             --upload.target=temporary-public-storage             --assert.failOnError=false
